---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret

platforms:
  - name: centos-6.5
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: debian-7
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
    - recipe[ganeti]
    attributes:
