---
provisioner:
  name: chef_solo

suites:
  - name: default
    run_list:
      - recipe[ganeti]
    excludes:
      - debian-7
  - name: master
    run_list:
      - recipe[ganeti-test]
      - recipe[ganeti]
    excludes:
      - debian-7
    provisioner:
      data_bags_path: test/integration/data_bags
      encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    attributes:
      ganeti:
        master-node: true
        cluster:
          disk-templates:
            - diskless
          master-netdev: lo
          enabled-hypervisors:
            - fake
          nic:
            mode: routed
            link: '100'
          name: ganeti.local
