---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
    driver_plugin: openstack
    driver_config:
      username: centos
      image_ref: "CentOS 6.6"
  - name: ubuntu-12.04
    driver_plugin: openstack
    driver_config:
      username: ubuntu
      image_ref: "Ubuntu 12.04"
    run_list:
      - recipe[apt::default]
  - name: debian-7
    driver_plugin: openstack
    driver_config:
      username: debian
      image_ref: "Debian 7"
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[ganeti]
    excludes: [ "debian-7" ]
  - name: master
    run_list:
      - recipe[ganeti-test]
      - recipe[ganeti]
    excludes: [ "debian-7" ]
    provisioner:
      data_bags_path: test/integration/data_bags
      encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    attributes:
      ganeti:
        master-node: true
        cluster:
          disk-templates:
            - "diskless"
          master-netdev: "lo"
          enabled-hypervisors:
            - "fake"
          nic:
            mode: "routed"
            link: "100"
          name: "ganeti.local"
