---
suites:
  - name: default
    run_list:
      - recipe[ganeti]
  - name: master
    run_list:
      - recipe[ganeti-test]
      - recipe[ganeti]
    provisioner:
      data_bags_path: test/integration/data_bags
      encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    attributes:
      ganeti:
        master-node: true
        cluster:
          disk-templates:
            - "diskless"
          master-netdev: "lo"
          enabled-hypervisors:
            - "fake"
          nic:
            mode: "routed"
            link: "100"
          name: "ganeti.local"
