---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  attributes:
    ganeti:
      drbd: false
      cluster:
        disk-templates:
          - "diskless"
        master-netdev: "lo"
        enabled-hypervisors:
          - "fake"
        nic:
          mode: "routed"
          link: "100"
        name: "ganeti.local"

transport:
  name: ssh

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[ganeti]
    data_bags_path: ''
  - name: master
    run_list:
      - recipe[ganeti-test]
      - recipe[ganeti]
    attributes:
      ganeti:
        master-node: true
  - name: drbd
    run_list:
      - recipe[ganeti-test]
      - recipe[ganeti]
    attributes:
      ganeti:
        master-node: true
        drbd: true
  - name: kvm
    run_list:
      - recipe[ganeti]
    attributes:
      ganeti:
        hypervisor: kvm
  - name: instance_image
    run_list:
      - recipe[ganeti::instance_image]
      - recipe[ganeti-test::instance_image_variant]
      - recipe[ganeti-test::instance_image_instance]
      - recipe[ganeti-test::instance_image_subnet]
      - recipe[ganeti-test::instance_image_hook]
