name             'ganeti'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/ganeti'
issues_url       'https://github.com/osuosl-cookbooks/ganeti/issues'
license          'Apache-2.0'
chef_version     '>= 12.18' if respond_to?(:chef_version)
description      'Installs/Configures ganeti'
long_description 'Installs/Configures ganeti'
version          '1.5.1'
supports         'ubuntu', '~> 14.04'
supports         'centos', '~> 6.0'
supports         'centos', '~> 7.0'

depends          'apt'
depends          'kernel-modules'
depends          'lvm'
depends          'yum'
depends          'yum-elrepo'
depends          'yum-epel'
depends          'hostsfile'
