name             'ganeti-test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures ganeti-test'
long_description ''
version          '0.1.0'
depends          'ganeti'
